# Generated by Django 2.1.7 on 2019-11-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
