# Generated by Django 2.1.7 on 2019-11-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergykitmain', '0002_delete_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_ID', models.CharField(max_length=20, null=True)),
                ('al_PW', models.CharField(max_length=20, null=True)),
                ('al_Name', models.CharField(max_length=20, null=True)),
                ('al_Email', models.CharField(max_length=50, null=True)),
                ('al_Gender', models.CharField(max_length=1, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
