# Generated by Django 2.1.7 on 2019-11-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
