# Generated by Django 2.1.14 on 2019-12-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0004_remove_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Al_CreateDate', models.DateTimeField(null=True)),
                ('Al_Files', models.FileField(blank=True, null=True, upload_to='')),
                ('fish_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flour_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('milk_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meat_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fruit_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cheese_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alcohol_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('egg_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chichen_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vegetable_al', models.DecimalField(decimal_places=2, max_digits=5)),
                ('User_Allergy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allergykitmain.User')),
            ],
        ),
    ]
