# Generated by Django 2.1.14 on 2019-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0005_usrallergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrallergy',
            name='alcohol_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='cheese_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='chichen_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='egg_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fish_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='flour_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fruit_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='meat_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='milk_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='vegetable_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
