# Generated by Django 2.1.14 on 2019-12-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0006_auto_20191201_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrallergy',
            old_name='chichen_al',
            new_name='chicken_al',
        ),
    ]
