# Generated by Django 2.1.14 on 2019-12-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0007_auto_20191201_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrallergy',
            name='alcohol_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='cheese_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='chicken_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='egg_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fish_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='flour_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fruit_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='meat_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='milk_al',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='vegetable_al',
            field=models.CharField(max_length=6),
        ),
    ]
