# Generated by Django 2.1.7 on 2019-12-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0008_auto_20191201_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usrallergy',
            options={'get_latest_by': ['Al_CreateDate']},
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='alcohol_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='cheese_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='chicken_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='egg_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fish_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='flour_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='fruit_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='meat_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='milk_al',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='usrallergy',
            name='vegetable_al',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
