# Generated by Django 2.1.7 on 2019-12-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergykitmain', '0009_auto_20191215_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='al_Birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='al_Height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='al_Weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
